# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: dipjyotimetia/hybridtestframework:2.0

steps:

- script: |
    set -ex
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo apt-get install ./google-chrome-stable_current_amd64.deb
  displayName: 'Install chrome driver'

- script: gradle task E2E
  displayName: 'End to End Test'
