# Complete infra creation for selenium chrome/firefox and owasp security testing

version: '3'

services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 25
    ports:
      - "5050:5050"
    volumes:
      - "./build/allure-results:/app/allure-results"
      - "./build/allure-reports:/app/default-reports"

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"

  firefox:
    image: selenium/node-firefox:4.1.2
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:4.1.2
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:4.1.2
    ports:
      - "4444:4444"

  zaproxy:
    image: owasp/zap2docker-stable:latest
    command: [
      #"zap.sh",
      "zap-x.sh",
      #"zap-webswing.sh",
      "-daemon",
      "-host", "0.0.0.0", "-port", "8082",
      "-config", "api.disablekey=true",
      "-config", "api.addrs.addr.name=.*",
      "-config", "api.addrs.addr.regex=true",
      "-config", "api.key=d025okl6n7blpkrr0iee6c7hsi",
      #"-addoninstall FOOXYZ",
      "-addonupdate"
    ]
    ports:
      - "127.0.0.1:8082:8082"