#  https://dev.to/goodidea/how-to-fake-aws-locally-with-localstack-27me
version: '3.0'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
      - EDGE_PORT=4566
      - SERVICES=s3,sns,sqs,lambda,dynamodb
      - DEBUG=1
    ports:
      - '4566:4566'
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"