site_name: HybridTestFramework
repo_name: dipjyotimetia/HybridTestFramework
repo_url: https://github.com/dipjyotimetia/HybridTestFramework
theme:
  name: material
  palette:
    primary: deep purple
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
  icon:
    repo: fontawesome/brands/git-alt
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dipjyotimetia
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/dipjyotimetia/
    - icon: fontawesome/brands/medium
      link: https://medium.com/@dipjyotimetia
copyright: 2021 <a href="https://github.com/dipjyotimetia">Dipjyoti Metia</a>.
