site_name: HybridTestFramework
repo_name: dipjyotimetia/HybridTestFramework
repo_url: https://github.com/dipjyotimetia/HybridTestFramework
theme:
  name: material
  palette:
    primary: deep purple
  prev_next_buttons_location: both
    navigation_depth: 4
    titles_only: False
    sticky_navigation: True
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
  icon:
    repo: fontawesome/brands/git-alt
markdown_extensions:
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: true
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dipjyotimetia
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/dipjyotimetia/
    - icon: fontawesome/brands/medium
      link: https://medium.com/@dipjyotimetia
copyright: 2021 <a href="https://github.com/dipjyotimetia">Dipjyoti Metia</a>.
