name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dipjyotimetia/hybridtestframework:2.0

    # give permission to Gradle to run the commands
    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      run: ./gradlew task e2e
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
