name: HybridTestFramework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: dipjyotimetia/hybridtestframework:2.0

    # give permission to Gradle to run the commands
    steps:
    - uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        chmod +x ./Driver/linux/chromedriver
        chmod +x ./Driver/linux/geckodriver
        ./gradlew task e2e
