name: HybridTestFramework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5.3.0
        # with:
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        # config-name: my-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  build:

    runs-on: ubuntu-latest
    container:
      image: dipjyotimetia/hybridtestframework:2.0

    # give permission to Gradle to run the commands
    steps:
    - uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permission for chromedriver
      run: chmod +x ./Driver/linux/chromedriver
    - name: Grant execute permission for geckodriver
      run: chmod +x ./Driver/linux/geckodriver
    - name: Build with Gradle
      run: ./gradlew task e2e
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
